mutation CreateTBDItem($title: String!, $status: String!, $userId: UUID!) @auth(level: USER) {
  tBDItem_insert(data: {title: $title, status: $status, userId: $userId, createdAt_expr: "request.time"})
}

query ListTBDItemsForUser($userId: UUID!) @auth(level: USER) {
  tBDItems(where: {userId: {eq: $userId}}) {
    id
    title
    status
    priority
    description
    tentativeDueDate
    category {
      id
      name
    }
    notes_on_tbdItem {
      id
      content
      createdAt
    }
  }
}

mutation CreateNote($tbdItemId: UUID!, $content: String!, $userId: UUID!) @auth(level: USER) {
  note_insert(data: {tbdItemId: $tbdItemId, content: $content, userId: $userId, createdAt_expr: "request.time"})
}

mutation UpdateTBDItemStatus($id: UUID!, $status: String!) @auth(level: USER) {
  tBDItem_update(key: {id: $id}, data: {status: $status})
}